code = int(input("Digite o código do produto: "))
nome = input("Digite o nome do produto: ")
quantidade = int(input("Digite a quantidade do produto: "))
preço = float(input("Digite o preço do produto: "))
total1 = (quantidade*preço)

print(f"------------------------")
print(f"Código: {code}")
print(f"Nome: {nome}")
print(f"quantidade: {quantidade}")
print(f"preço: {preço:.2f}")
print(f"------------------------")
print(f"O total a se pagar é: R${total1:.2f}")
print(f"------------------------")

code2 = int(input("Digite o código do produto: "))
nome2 = input("Digite o nome do produto: ")
quantidade2 = int(input("Digite a quantidade do produto: "))
preço2 = float(input("Digite o preço do produto: "))
total2 = (quantidade2*preço2)

print(f"------------------------")
print(f"Código: {code2}")
print(f"Nome: {nome}")
print(f"Quantidade: {quantidade2}")
print(f"Preço: {preço2:.2f}")
print(f"------------------------")
print(f"O total a se pagar é: R${total2}")
print(f"------------------------")

print(f"Total da compra: R${total1+total2:.2f}")
print(f"------------------------")